### ISSUE TITLE
DbContext is Disposed in EntityCreated event handler

### ISSUE THREAD

**Issue by exiled78** [aspnetboilerplate/aspnetboilerplate-samples#28]
Hi I get an error in this class : 

https://github.com/exiled78/aspnetboilerplate-samples/blob/Test_Disposed_Repo/SimpleTaskSystem-Core/src/Acme.SimpleTaskApp.Core/Tasks/TaskCreatedHandler.cs#L36

But all is ok here:

https://github.com/exiled78/aspnetboilerplate-samples/blob/Test_Disposed_Repo/SimpleTaskSystem-Core/src/Acme.SimpleTaskApp.Core/Tasks/TaskCreatingHandler.cs#L36

Obviously the only difference is one handles EntityCreated vs EntityCreating. Not sure if this is a bug, or my approach is wrong. 

Thanks!

**Comment by hikalkan** [comment]
Hi,

"GetAll works in EntityCreating, but not works in EntityCreated" is an expected case. Because GetAll() requires an open db connection (UOW - see doc: https://www.aspnetboilerplate.com/Pages/Documents/Unit-Of-Work#DocRepositoryGetAll) and Created event is triggered after UOW completed. If you add [UnitOfWork] attribute to HandleEvent and make this method virtual, it will work.

**Comment by exiled78** [comment]
@hikalkan Thanks!
